web:
  build: .
  command: 'bash -c ''node --optimize_for_size --max_old_space_size=460 --gc_interval=100 index.js'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
